const Language = {
  PORTUGUESE: 'portuguese',
  ENGLISH: 'english',
  SPANISH: 'spanish',
  FRENCH: 'french',
  GERMAN: 'german',
  ITALIAN: 'italian',
  JAPANESE: 'japanese',
  MANDARIN: 'mandarin',
  ARABIC: 'arabic',
  RUSSIAN: 'russian',
  HINDI: 'hindi',
  BENGALI: 'bengali',
  URDU: 'urdu',
  INDONESIAN: 'indonesian',
  TURKISH: 'turkish',
  KOREAN: 'korean',
  VIETNAMESE: 'vietnamese',
  POLISH: 'polish',
  DUTCH: 'dutch',
  GREEK: 'greek',
  ROMANIAN: 'romanian',
  THAI: 'thai',
  SWEDISH: 'swedish',
  HUNGARIAN: 'hungarian',
  CZECH: 'czech',
  FINNISH: 'finnish',
  HEBREW: 'hebrew',
  UKRAINIAN: 'ukrainian',
  NORWEGIAN: 'norwegian',
  DANISH: 'danish',
  SWAHILI: 'swahili',
  FILIPINO: 'filipino',
  MALAY: 'malay',
  SERBIAN: 'serbian',
  CROATIAN: 'croatian',
  SLOVAK: 'slovak',
  BULGARIAN: 'bulgarian',
  SLOVENIAN: 'slovenian',
  LITHUANIAN: 'lithuanian',
  LATVIAN: 'latvian',
  ESTONIAN: 'estonian',
  PERSIAN: 'persian',
};

module.exports = Language;
